Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = ENV["DEV_DIR"] + "jiss-provision/playbooks/init.yml"
  end

  config.vm.provision "shell" do |shell|
    shell.inline = "ufw allow 3306"
  end

  config.vm.provision "shell", run: "always" do |shell|
    shell.inline = "ifconfig"
  end
end